FROM registry.cn-beijing.aliyuncs.com/ifmuse/kuandd.piling.localhost:1.0

MAINTAINER kuandd <sanye@kuandd>
WORKDIR /usr/local/php/sbin
CMD ["php-fpm"]
#RUN /usr/local/php/sbin/php-fpm
#["/usr/local/php/sbin/php-fpm"]
      # /usr/local/php/sbin/php-fpm