FROM registry.cn-beijing.aliyuncs.com/ifmuse/kuandd.piling.localhost:1.0

MAINTAINER kuandd <sanye@kuandd>
RUN /usr/local/php/sbin/php-fpm
#["/usr/local/php/sbin/php-fpm"]
      # /usr/local/php/sbin/php-fpm